### ISSUE TITLE
Firefox not running on latest for windows 10

### ISSUE THREAD

**Issue by KeyanNamaghi** [browserstack/browserstack-cypress-cli#369] opened 2022-07-12 09:25 UTC
```
You might notice that a few specs are missing in the test report as Cypress failed to run a few specs in the following environments:
Windows 10 firefox102
```

Browser: firefox
Version: Latest
OS: Windows 10
Cypress: 9 (9.6.1)

Expected:
* runs firefox100 and runs as expected

Actual:
* runs firefox102 and fails to run

According to https://www.browserstack.com/list-of-browsers-and-platforms/cypress_testing it should only be running 100.

Note: I haven't had time to test any other OS with firefox

(Apologies if this isn't the right place to be posting this)

**Comment by pranavj1001** [comment] 2022-07-12 11:38
Hey @KeyanNamaghi, currently there's an open issue on cypress not able to connect to Firefox v101 and above browsers ([link](https://github.com/cypress-io/cypress/issues/22086)). Till the issue is not fixed, please run the sessions on Firefox v100 and below or use other browsers.

**Comment by KeyanNamaghi** [comment] 2022-07-12 12:34
Thanks for the update, hopefully it gets fixed soon 👍

**Comment by pranavj1001** [comment] 2022-08-08 05:49
This has been fixed with the release of Firefox v103. However, sessions won't still work on Firefox 101 and 102. Closing this issue for now. Feel free to reopen or create a new one if this issue is not resolved yet.

**Closed by pranavj1001** 2022-08-08 05:49 UTC
