### ISSUE TITLE
No video is captured in BS

### ISSUE THREAD

**Issue by ivan-xue-prospa** [browserstack/browserstack-cypress-cli#123] opened 2021-03-08 23:20 UTC
I set video as true in cypress.json file, but when I check the session in BS, there are no videos captured.

**Comment by shawnlobo96** [comment] 2021-03-09 00:02
@ivan-xue-prospa Can you share the build ID with support@browserstack.com?

**Comment by ivan-xue-prospa** [comment] 2021-03-09 00:06
Dear Support

I was using browserstack-cypress-cli to run tests in BS and configured video as true in cypress.json, but there are no videos captured for the build - https://automate.browserstack.com/dashboard/v2/builds/d81a83798355b282a00b2dc1e949186dd878a73a


Ivan Xue
Software Developer in Test
T 1300 882 867
Lvl 1, 4-16 Yurong St, Sydney 2000
prospa.com
The information contained in this email is confidential. It is intended only for the stated addressee(s) and access to it by any other person is unauthorised. If you are not an addressee, you must not disclose, distribute, print, copy or circulate this information. Such unauthorised use may be unlawful. If you have received this email in error, please inform Prospa Advance Pty Ltd, immediately and delete it and all copies from your system. While Prospa Advance Pty Ltd makes every effort to keep our network free from viruses, we take no responsibility for any computer virus which might be transferred by way of this email.

**Comment by SagarGaniga** [comment] 2021-03-09 06:08
This is an issue from Cypress side (Chrome 87+ and Cypress versions below v6), explained here: https://github.com/cypress-io/cypress/issues/9265

They fixed it in v6, try running builds on v6+ using `cypress_version` as shown in https://www.browserstack.com/docs/automate/cypress/supported-versions

**Comment by suryart** [comment] 2021-03-12 14:50
Closing as the issue is explained in cypress-io/cypress#9265

**Closed by suryart** 2021-03-12 14:50 UTC
