### ISSUE TITLE
Cypress no longer supports cypress.json

### ISSUE THREAD

**Issue by Ross-mc** [browserstack/browserstack-cypress-cli#370] opened 2022-07-12 11:06 UTC
As of Cypress 10, cypress.json is no longer supported (https://docs.cypress.io/guides/references/configuration).

Browserstack-cypress-cli requires a json file in `cypress_config_file` and throws an invalid JSON parse error when I reference `cypress.config.ts` (which is to be expected as its not JSON).

```[12/07/2022, 12:05:20] - info: Reading config from /Users/ross/dev/worker-classification-ui/browserstack.json
(node:10945) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[12/07/2022, 12:05:20] - error:  
{
  message: 'Unexpected token i in JSON at position 0',
  stack: 'SyntaxError: Unexpected token i in JSON at position 0\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at Object.exports.getCypressJSON (/Users/ross/.nvm/versions/node/v14.18.1/lib/node_modules/browserstack-cypress-cli/bin/helpers/utils.js:1082:24)\n' +
    '    at Object.exports.setProjectId (/Users/ross/.nvm/versions/node/v14.18.1/lib/node_modules/browserstack-cypress-cli/bin/helpers/utils.js:363:28)\n' +
    '    at Object.exports.setRecordCaps (/Users/ross/.nvm/versions/node/v14.18.1/lib/node_modules/browserstack-cypress-cli/bin/helpers/utils.js:371:45)\n' +
    '    at /Users/ross/.nvm/versions/node/v14.18.1/lib/node_modules/browserstack-cypress-cli/bin/commands/runs.js:98:11\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)'
}```



Will support for cypress.config.ts be added?

**Comment by dspaeth-breuni** [comment] 2022-07-14 07:05
more or less a duplicate of #342 ?

**Comment by Ross-mc** [comment] 2022-07-14 12:02
> more or less a duplicate of #342 ?

There is some duplication, but I am highlighting a specific issue about Cypress config and curious if there is a workaround with the current version of browserstack, I haven't been able to find anything so far.

**Comment by Aditya-GBS** [comment] 2022-07-18 11:25
BrowserStack does not support Cypress 10 as of now.
The implementation of new folder structure of Cypress 10 might take some more time
Meanwhile, Cypress.json is still supported so you may use it until then

**Comment by rrsai** [comment] 2022-08-04 22:22
If you're like me, you wanted to use both, and so as a workaround, point the browserstack.json config file path at a simple config file, e.g.

./cypress/blank.json and use that config file for browserstack with overrides for environment variables in your local dev environment!

**Comment by pranavj1001** [comment] 2022-10-14 17:11
Closing this issue as BrowserStack supports Cypress 10. Make sure you update to the latest CLI. Feel free to open another issue if you're still facing any problems.

**Closed by pranavj1001** 2022-10-14 17:11 UTC
